import { IBuilding } from "../domain/building"

export const FakeBuildingsData: IBuilding[] = [
	{
		id: 0,
		name: "Bâtiment 1",
		plans: [
			{
				id: 0,
				name: "RDC",
				picture: {
					src: "",
					alt: "Plan du RDC",
				},
				collaborators: [
					{
						id: 0,
						firstname: "John",
						lastname: "Doe",
						deskId: 0,
					},
					{
						id: 1,
						firstname: "John",
						lastname: "Doe",
						deskId: 1,
					},
					{
						id: 2,
						firstname: "John",
						lastname: "Doe",
						deskId: 2,
					},
					{
						id: 3,
						firstname: "John",
						lastname: "Doe",
						deskId: 3,
					},
					{
						id: 4,
						firstname: "John",
						lastname: "Doe",
						deskId: 4,
					},
					{
						id: 5,
						firstname: "John",
						lastname: "Doe",
						deskId: 5,
					},
					{
						id: 6,
						firstname: "John",
						lastname: "Doe",
						deskId: 6,
					},
					{
						id: 7,
						firstname: "John",
						lastname: "Doe",
						deskId: 7,
					},
					{
						id: 8,
						firstname: "John",
						lastname: "Doe",
						deskId: 8,
					},
					{
						id: 9,
						firstname: "John",
						lastname: "Doe",
						deskId: 9,
					},
					{
						id: 10,
						firstname: "John",
						lastname: "Doe",
						deskId: 10,
					},
					{
						id: 11,
						firstname: "John",
						lastname: "Doe",
						deskId: 11,
					},
					{
						id: 12,
						firstname: "John",
						lastname: "Doe",
						deskId: 12,
					},
					{
						id: 13,
						firstname: "John",
						lastname: "Doe",
						deskId: 13,
					},
					{
						id: 14,
						firstname: "John",
						lastname: "Doe",
						deskId: 14,
					},
					{
						id: 15,
						firstname: "John",
						lastname: "Doe",
						deskId: 15,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
			{
				id: 1,
				name: "1er Etage",
				picture: {
					src: "",
					alt: "Plan du 1er Etage",
				},
				collaborators: [
					{
						id: 16,
						firstname: "John",
						lastname: "Doe",
						deskId: 16,
					},
					{
						id: 17,
						firstname: "John",
						lastname: "Doe",
						deskId: 17,
					},
					{
						id: 18,
						firstname: "John",
						lastname: "Doe",
						deskId: 18,
					},
					{
						id: 19,
						firstname: "John",
						lastname: "Doe",
						deskId: 19,
					},
					{
						id: 20,
						firstname: "John",
						lastname: "Doe",
						deskId: 20,
					},
					{
						id: 21,
						firstname: "John",
						lastname: "Doe",
						deskId: 21,
					},
					{
						id: 22,
						firstname: "John",
						lastname: "Doe",
						deskId: 22,
					},
					{
						id: 23,
						firstname: "John",
						lastname: "Doe",
						deskId: 23,
					},
					{
						id: 24,
						firstname: "John",
						lastname: "Doe",
						deskId: 24,
					},
					{
						id: 25,
						firstname: "John",
						lastname: "Doe",
						deskId: 25,
					},
					{
						id: 26,
						firstname: "John",
						lastname: "Doe",
						deskId: 26,
					},
					{
						id: 27,
						firstname: "John",
						lastname: "Doe",
						deskId: 27,
					},
					{
						id: 28,
						firstname: "John",
						lastname: "Doe",
						deskId: 28,
					},
					{
						id: 29,
						firstname: "John",
						lastname: "Doe",
						deskId: 29,
					},
					{
						id: 30,
						firstname: "John",
						lastname: "Doe",
						deskId: 30,
					},
					{
						id: 31,
						firstname: "John",
						lastname: "Doe",
						deskId: 31,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
			{
				id: 2,
				name: "2nd Etage",
				picture: {
					src: "",
					alt: "Plan du 2nd Etage",
				},
				collaborators: [
					{
						id: 32,
						firstname: "John",
						lastname: "Doe",
						deskId: 32,
					},
					{
						id: 33,
						firstname: "John",
						lastname: "Doe",
						deskId: 33,
					},
					{
						id: 34,
						firstname: "John",
						lastname: "Doe",
						deskId: 34,
					},
					{
						id: 35,
						firstname: "John",
						lastname: "Doe",
						deskId: 35,
					},
					{
						id: 36,
						firstname: "John",
						lastname: "Doe",
						deskId: 36,
					},
					{
						id: 37,
						firstname: "John",
						lastname: "Doe",
						deskId: 37,
					},
					{
						id: 38,
						firstname: "John",
						lastname: "Doe",
						deskId: 38,
					},
					{
						id: 39,
						firstname: "John",
						lastname: "Doe",
						deskId: 39,
					},
					{
						id: 40,
						firstname: "John",
						lastname: "Doe",
						deskId: 40,
					},
					{
						id: 41,
						firstname: "John",
						lastname: "Doe",
						deskId: 41,
					},
					{
						id: 42,
						firstname: "John",
						lastname: "Doe",
						deskId: 42,
					},
					{
						id: 43,
						firstname: "John",
						lastname: "Doe",
						deskId: 43,
					},
					{
						id: 44,
						firstname: "John",
						lastname: "Doe",
						deskId: 44,
					},
					{
						id: 45,
						firstname: "John",
						lastname: "Doe",
						deskId: 45,
					},
					{
						id: 46,
						firstname: "John",
						lastname: "Doe",
						deskId: 46,
					},
					{
						id: 47,
						firstname: "John",
						lastname: "Doe",
						deskId: 47,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
			{
				id: 3,
				name: "3ème Etage",
				picture: {
					src: "",
					alt: "Plan du 3ème Etage",
				},
				collaborators: [
					{
						id: 48,
						firstname: "John",
						lastname: "Doe",
						deskId: 48,
					},
					{
						id: 49,
						firstname: "John",
						lastname: "Doe",
						deskId: 49,
					},
					{
						id: 50,
						firstname: "John",
						lastname: "Doe",
						deskId: 50,
					},
					{
						id: 51,
						firstname: "John",
						lastname: "Doe",
						deskId: 51,
					},
					{
						id: 52,
						firstname: "John",
						lastname: "Doe",
						deskId: 52,
					},
					{
						id: 53,
						firstname: "John",
						lastname: "Doe",
						deskId: 53,
					},
					{
						id: 54,
						firstname: "John",
						lastname: "Doe",
						deskId: 54,
					},
					{
						id: 55,
						firstname: "John",
						lastname: "Doe",
						deskId: 55,
					},
					{
						id: 56,
						firstname: "John",
						lastname: "Doe",
						deskId: 56,
					},
					{
						id: 57,
						firstname: "John",
						lastname: "Doe",
						deskId: 57,
					},
					{
						id: 58,
						firstname: "John",
						lastname: "Doe",
						deskId: 58,
					},
					{
						id: 59,
						firstname: "John",
						lastname: "Doe",
						deskId: 59,
					},
					{
						id: 60,
						firstname: "John",
						lastname: "Doe",
						deskId: 60,
					},
					{
						id: 61,
						firstname: "John",
						lastname: "Doe",
						deskId: 61,
					},
					{
						id: 62,
						firstname: "John",
						lastname: "Doe",
						deskId: 62,
					},
					{
						id: 63,
						firstname: "John",
						lastname: "Doe",
						deskId: 63,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
		],
		receptionMaxCapacity: 64,
		currentReceptionCapacity: 64,
		officesNumber: 64,
		occupancyStatistics: 100,
		picture: {
			src: "/images/buildings/batiment-1.png",
			alt: "Image du Bâtiment A",
		},
	},
	{
		id: 1,
		name: "Bâtiment 2",
		plans: [
			{
				id: 0,
				name: "RDC",
				picture: {
					src: "",
					alt: "Plan du RDC",
				},
				collaborators: [
					{
						id: 0,
						firstname: "John",
						lastname: "Doe",
						deskId: 0,
					},
					{
						id: 1,
						firstname: "John",
						lastname: "Doe",
						deskId: 1,
					},
					{
						id: 2,
						firstname: "John",
						lastname: "Doe",
						deskId: 2,
					},
					{
						id: 3,
						firstname: "John",
						lastname: "Doe",
						deskId: 3,
					},
					{
						id: 4,
						firstname: "John",
						lastname: "Doe",
						deskId: 4,
					},
					{
						id: 5,
						firstname: "John",
						lastname: "Doe",
						deskId: 5,
					},
					{
						id: 6,
						firstname: "John",
						lastname: "Doe",
						deskId: 6,
					},
					{
						id: 7,
						firstname: "John",
						lastname: "Doe",
						deskId: 7,
					},
					{
						id: 8,
						firstname: "John",
						lastname: "Doe",
						deskId: 8,
					},
					{
						id: 9,
						firstname: "John",
						lastname: "Doe",
						deskId: 9,
					},
					{
						id: 10,
						firstname: "John",
						lastname: "Doe",
						deskId: 10,
					},
					{
						id: 11,
						firstname: "John",
						lastname: "Doe",
						deskId: 11,
					},
					{
						id: 12,
						firstname: "John",
						lastname: "Doe",
						deskId: 12,
					},
					{
						id: 13,
						firstname: "John",
						lastname: "Doe",
						deskId: 13,
					},
					{
						id: 14,
						firstname: "John",
						lastname: "Doe",
						deskId: 14,
					},
					{
						id: 15,
						firstname: "John",
						lastname: "Doe",
						deskId: 15,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
			{
				id: 1,
				name: "1er Etage",
				picture: {
					src: "",
					alt: "Plan du 1er Etage",
				},
				collaborators: [
					{
						id: 16,
						firstname: "John",
						lastname: "Doe",
						deskId: 16,
					},
					{
						id: 17,
						firstname: "John",
						lastname: "Doe",
						deskId: 17,
					},
					{
						id: 18,
						firstname: "John",
						lastname: "Doe",
						deskId: 18,
					},
					{
						id: 19,
						firstname: "John",
						lastname: "Doe",
						deskId: 19,
					},
					{
						id: 20,
						firstname: "John",
						lastname: "Doe",
						deskId: 20,
					},
					{
						id: 21,
						firstname: "John",
						lastname: "Doe",
						deskId: 21,
					},
					{
						id: 22,
						firstname: "John",
						lastname: "Doe",
						deskId: 22,
					},
					{
						id: 23,
						firstname: "John",
						lastname: "Doe",
						deskId: 23,
					},
					{
						id: 24,
						firstname: "John",
						lastname: "Doe",
						deskId: 24,
					},
					{
						id: 25,
						firstname: "John",
						lastname: "Doe",
						deskId: 25,
					},
					{
						id: 26,
						firstname: "John",
						lastname: "Doe",
						deskId: 26,
					},
					{
						id: 27,
						firstname: "John",
						lastname: "Doe",
						deskId: 27,
					},
					{
						id: 28,
						firstname: "John",
						lastname: "Doe",
						deskId: 28,
					},
					{
						id: 29,
						firstname: "John",
						lastname: "Doe",
						deskId: 29,
					},
					{
						id: 30,
						firstname: "John",
						lastname: "Doe",
						deskId: 30,
					},
					{
						id: 31,
						firstname: "John",
						lastname: "Doe",
						deskId: 31,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
			{
				id: 2,
				name: "2nd Etage",
				picture: {
					src: "",
					alt: "Plan du 2nd Etage",
				},
				collaborators: [
					{
						id: 32,
						firstname: "John",
						lastname: "Doe",
						deskId: 32,
					},
					{
						id: 33,
						firstname: "John",
						lastname: "Doe",
						deskId: 33,
					},
					{
						id: 34,
						firstname: "John",
						lastname: "Doe",
						deskId: 34,
					},
					{
						id: 35,
						firstname: "John",
						lastname: "Doe",
						deskId: 35,
					},
					{
						id: 36,
						firstname: "John",
						lastname: "Doe",
						deskId: 36,
					},
					{
						id: 37,
						firstname: "John",
						lastname: "Doe",
						deskId: 37,
					},
					{
						id: 38,
						firstname: "John",
						lastname: "Doe",
						deskId: 38,
					},
					{
						id: 39,
						firstname: "John",
						lastname: "Doe",
						deskId: 39,
					},
					{
						id: 40,
						firstname: "John",
						lastname: "Doe",
						deskId: 40,
					},
					{
						id: 41,
						firstname: "John",
						lastname: "Doe",
						deskId: 41,
					},
					{
						id: 42,
						firstname: "John",
						lastname: "Doe",
						deskId: 42,
					},
					{
						id: 43,
						firstname: "John",
						lastname: "Doe",
						deskId: 43,
					},
					{
						id: 44,
						firstname: "John",
						lastname: "Doe",
						deskId: 44,
					},
					{
						id: 45,
						firstname: "John",
						lastname: "Doe",
						deskId: 45,
					},
					{
						id: 46,
						firstname: "John",
						lastname: "Doe",
						deskId: 46,
					},
					{
						id: 47,
						firstname: "John",
						lastname: "Doe",
						deskId: 47,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
			{
				id: 3,
				name: "3ème Etage",
				picture: {
					src: "",
					alt: "Plan du 3ème Etage",
				},
				collaborators: [
					{
						id: 48,
						firstname: "John",
						lastname: "Doe",
						deskId: 48,
					},
					{
						id: 49,
						firstname: "John",
						lastname: "Doe",
						deskId: 149,
					},
					{
						id: 50,
						firstname: "John",
						lastname: "Doe",
						deskId: 50,
					},
					{
						id: 51,
						firstname: "John",
						lastname: "Doe",
						deskId: 51,
					},
					{
						id: 52,
						firstname: "John",
						lastname: "Doe",
						deskId: 52,
					},
					{
						id: 53,
						firstname: "John",
						lastname: "Doe",
						deskId: 53,
					},
					{
						id: 54,
						firstname: "John",
						lastname: "Doe",
						deskId: 54,
					},
					{
						id: 55,
						firstname: "John",
						lastname: "Doe",
						deskId: 55,
					},
					{
						id: 56,
						firstname: "John",
						lastname: "Doe",
						deskId: 56,
					},
					{
						id: 57,
						firstname: "John",
						lastname: "Doe",
						deskId: 57,
					},
					{
						id: 58,
						firstname: "John",
						lastname: "Doe",
						deskId: 58,
					},
					{
						id: 59,
						firstname: "John",
						lastname: "Doe",
						deskId: 59,
					},
					{
						id: 60,
						firstname: "John",
						lastname: "Doe",
						deskId: 60,
					},
					{
						id: 61,
						firstname: "John",
						lastname: "Doe",
						deskId: 61,
					},
					{
						id: 62,
						firstname: "John",
						lastname: "Doe",
						deskId: 62,
					},
					{
						id: 63,
						firstname: "John",
						lastname: "Doe",
						deskId: 63,
					},
				],
				receptionMaxCapacity: 16,
				currentReceptionCapacity: 16,
			},
		],
		receptionMaxCapacity: 64,
		currentReceptionCapacity: 64,
		officesNumber: 64,
		occupancyStatistics: 100,
		picture: {
			src: "/images/buildings/batiment-2.png",
			alt: "Image du Bâtiment B",
		},
	},
]
