import { IBuilding } from "../domain/building"

export const FakeBuildingsData: IBuilding[] = [
	{
		id: 0,
		nom: "Bâtiment 1",
		etages: [
			{
				id: 0,
				plans: [
					{
						id: 0,
						nom: "RDC",
						picture: {
							src: "",
							alt: "Plan du RDC",
						},
						collaborators: [
							{
								id: 0,
								firstName: "John",
								lastName: "Doe",
								deskId: 0,
							},
							{
								id: 1,
								firstName: "John",
								lastName: "Doe",
								deskId: 1,
							},
							{
								id: 2,
								firstName: "John",
								lastName: "Doe",
								deskId: 2,
							},
							{
								id: 3,
								firstName: "John",
								lastName: "Doe",
								deskId: 3,
							},
							{
								id: 4,
								firstName: "John",
								lastName: "Doe",
								deskId: 4,
							},
							{
								id: 5,
								firstName: "John",
								lastName: "Doe",
								deskId: 5,
							},
							{
								id: 6,
								firstName: "John",
								lastName: "Doe",
								deskId: 6,
							},
							{
								id: 7,
								firstName: "John",
								lastName: "Doe",
								deskId: 7,
							},
							{
								id: 8,
								firstName: "John",
								lastName: "Doe",
								deskId: 8,
							},
							{
								id: 9,
								firstName: "John",
								lastName: "Doe",
								deskId: 9,
							},
							{
								id: 10,
								firstName: "John",
								lastName: "Doe",
								deskId: 10,
							},
							{
								id: 11,
								firstName: "John",
								lastName: "Doe",
								deskId: 11,
							},
							{
								id: 12,
								firstName: "John",
								lastName: "Doe",
								deskId: 12,
							},
							{
								id: 13,
								firstName: "John",
								lastName: "Doe",
								deskId: 13,
							},
							{
								id: 14,
								firstName: "John",
								lastName: "Doe",
								deskId: 14,
							},
							{
								id: 15,
								firstName: "John",
								lastName: "Doe",
								deskId: 15,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 0,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [0],
							},
							{
								id: 1,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [1],
							},
							{
								id: 2,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [2],
							},
							{
								id: 3,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [3],
							},
							{
								id: 4,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [4],
							},
							{
								id: 5,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [5],
							},
							{
								id: 6,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [6],
							},
							{
								id: 7,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [7],
							},
							{
								id: 8,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [8],
							},
							{
								id: 9,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [9],
							},
							{
								id: 10,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [10],
							},
							{
								id: 11,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [11],
							},
							{
								id: 12,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [12],
							},
							{
								id: 13,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [13],
							},
							{
								id: 14,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [14],
							},
							{
								id: 15,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [15],
							},
						],
					},
				],
			},
			{
				id: 1,
				plans: [
					{
						id: 0,
						nom: "1er Etage",
						picture: {
							src: "",
							alt: "Plan du 1er Etage",
						},
						collaborators: [
							{
								id: 16,
								firstName: "John",
								lastName: "Doe",
								deskId: 16,
							},
							{
								id: 17,
								firstName: "John",
								lastName: "Doe",
								deskId: 17,
							},
							{
								id: 18,
								firstName: "John",
								lastName: "Doe",
								deskId: 18,
							},
							{
								id: 19,
								firstName: "John",
								lastName: "Doe",
								deskId: 19,
							},
							{
								id: 20,
								firstName: "John",
								lastName: "Doe",
								deskId: 20,
							},
							{
								id: 21,
								firstName: "John",
								lastName: "Doe",
								deskId: 21,
							},
							{
								id: 22,
								firstName: "John",
								lastName: "Doe",
								deskId: 22,
							},
							{
								id: 23,
								firstName: "John",
								lastName: "Doe",
								deskId: 23,
							},
							{
								id: 24,
								firstName: "John",
								lastName: "Doe",
								deskId: 24,
							},
							{
								id: 25,
								firstName: "John",
								lastName: "Doe",
								deskId: 25,
							},
							{
								id: 26,
								firstName: "John",
								lastName: "Doe",
								deskId: 26,
							},
							{
								id: 27,
								firstName: "John",
								lastName: "Doe",
								deskId: 27,
							},
							{
								id: 28,
								firstName: "John",
								lastName: "Doe",
								deskId: 28,
							},
							{
								id: 29,
								firstName: "John",
								lastName: "Doe",
								deskId: 29,
							},
							{
								id: 30,
								firstName: "John",
								lastName: "Doe",
								deskId: 30,
							},
							{
								id: 31,
								firstName: "John",
								lastName: "Doe",
								deskId: 31,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 16,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [16],
							},
							{
								id: 17,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [17],
							},
							{
								id: 18,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [18],
							},
							{
								id: 19,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [19],
							},
							{
								id: 20,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [20],
							},
							{
								id: 21,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [21],
							},
							{
								id: 22,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [22],
							},
							{
								id: 23,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [23],
							},
							{
								id: 24,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [24],
							},
							{
								id: 25,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [25],
							},
							{
								id: 27,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [27],
							},
							{
								id: 28,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [28],
							},
							{
								id: 29,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [29],
							},
							{
								id: 30,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [30],
							},
							{
								id: 31,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [31],
							},
							{
								id: 32,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [32],
							},
						],
					},
				],
			},
			{
				id: 2,
				plans: [
					{
						id: 0,
						nom: "2nd Etage",
						picture: {
							src: "",
							alt: "Plan du 2nd Etage",
						},
						collaborators: [
							{
								id: 32,
								firstName: "John",
								lastName: "Doe",
								deskId: 32,
							},
							{
								id: 33,
								firstName: "John",
								lastName: "Doe",
								deskId: 33,
							},
							{
								id: 34,
								firstName: "John",
								lastName: "Doe",
								deskId: 34,
							},
							{
								id: 35,
								firstName: "John",
								lastName: "Doe",
								deskId: 35,
							},
							{
								id: 36,
								firstName: "John",
								lastName: "Doe",
								deskId: 36,
							},
							{
								id: 37,
								firstName: "John",
								lastName: "Doe",
								deskId: 37,
							},
							{
								id: 38,
								firstName: "John",
								lastName: "Doe",
								deskId: 38,
							},
							{
								id: 39,
								firstName: "John",
								lastName: "Doe",
								deskId: 39,
							},
							{
								id: 40,
								firstName: "John",
								lastName: "Doe",
								deskId: 40,
							},
							{
								id: 41,
								firstName: "John",
								lastName: "Doe",
								deskId: 41,
							},
							{
								id: 42,
								firstName: "John",
								lastName: "Doe",
								deskId: 42,
							},
							{
								id: 43,
								firstName: "John",
								lastName: "Doe",
								deskId: 43,
							},
							{
								id: 44,
								firstName: "John",
								lastName: "Doe",
								deskId: 44,
							},
							{
								id: 45,
								firstName: "John",
								lastName: "Doe",
								deskId: 45,
							},
							{
								id: 46,
								firstName: "John",
								lastName: "Doe",
								deskId: 46,
							},
							{
								id: 47,
								firstName: "John",
								lastName: "Doe",
								deskId: 47,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 33,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [33],
							},
							{
								id: 34,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [34],
							},
							{
								id: 35,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [35],
							},
							{
								id: 36,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [36],
							},
							{
								id: 37,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [37],
							},
							{
								id: 38,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [38],
							},
							{
								id: 39,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [39],
							},
							{
								id: 40,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [40],
							},
							{
								id: 41,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [41],
							},
							{
								id: 42,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [42],
							},
							{
								id: 43,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [43],
							},
							{
								id: 44,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [44],
							},
							{
								id: 45,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [45],
							},
							{
								id: 46,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [46],
							},
							{
								id: 47,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [47],
							},
							{
								id: 48,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [48],
							},
						],
					},
				],
			},
			{
				id: 3,
				plans: [
					{
						id: 0,
						nom: "3ème Etage",
						picture: {
							src: "",
							alt: "Plan du 3ème Etage",
						},
						collaborators: [
							{
								id: 48,
								firstName: "John",
								lastName: "Doe",
								deskId: 48,
							},
							{
								id: 49,
								firstName: "John",
								lastName: "Doe",
								deskId: 49,
							},
							{
								id: 50,
								firstName: "John",
								lastName: "Doe",
								deskId: 50,
							},
							{
								id: 51,
								firstName: "John",
								lastName: "Doe",
								deskId: 51,
							},
							{
								id: 52,
								firstName: "John",
								lastName: "Doe",
								deskId: 52,
							},
							{
								id: 53,
								firstName: "John",
								lastName: "Doe",
								deskId: 53,
							},
							{
								id: 54,
								firstName: "John",
								lastName: "Doe",
								deskId: 54,
							},
							{
								id: 55,
								firstName: "John",
								lastName: "Doe",
								deskId: 55,
							},
							{
								id: 56,
								firstName: "John",
								lastName: "Doe",
								deskId: 56,
							},
							{
								id: 57,
								firstName: "John",
								lastName: "Doe",
								deskId: 57,
							},
							{
								id: 58,
								firstName: "John",
								lastName: "Doe",
								deskId: 58,
							},
							{
								id: 59,
								firstName: "John",
								lastName: "Doe",
								deskId: 59,
							},
							{
								id: 60,
								firstName: "John",
								lastName: "Doe",
								deskId: 60,
							},
							{
								id: 61,
								firstName: "John",
								lastName: "Doe",
								deskId: 61,
							},
							{
								id: 62,
								firstName: "John",
								lastName: "Doe",
								deskId: 62,
							},
							{
								id: 63,
								firstName: "John",
								lastName: "Doe",
								deskId: 63,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 49,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [49],
							},
							{
								id: 50,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [50],
							},
							{
								id: 51,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [51],
							},
							{
								id: 52,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [52],
							},
							{
								id: 53,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [53],
							},
							{
								id: 54,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [54],
							},
							{
								id: 55,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [55],
							},
							{
								id: 56,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [56],
							},
							{
								id: 57,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [57],
							},
							{
								id: 58,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [58],
							},
							{
								id: 59,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [59],
							},
							{
								id: 60,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [60],
							},
							{
								id: 61,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [61],
							},
							{
								id: 62,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [62],
							},
							{
								id: 63,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [63],
							},
							{
								id: 64,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [64],
							},
						],
					},
				],
			},
		],
		receptionMaxcapacity: 64,
		currentReceptionCapacity: 64,
		officesNumber: 64,
		occupancyStatistics: 100,
		picture: {
			src: "/images/buildings/batiment-1.png",
			alt: "Image du Bâtiment A",
		},
	},
	{
		id: 1,
		nom: "Bâtiment 2",
		etages: [
			{
				id: 0,
				plans: [
					{
						id: 0,
						nom: "RDC",
						picture: {
							src: "",
							alt: "Plan du RDC",
						},
						collaborators: [
							{
								id: 0,
								firstName: "John",
								lastName: "Doe",
								deskId: 0,
							},
							{
								id: 1,
								firstName: "John",
								lastName: "Doe",
								deskId: 1,
							},
							{
								id: 2,
								firstName: "John",
								lastName: "Doe",
								deskId: 2,
							},
							{
								id: 3,
								firstName: "John",
								lastName: "Doe",
								deskId: 3,
							},
							{
								id: 4,
								firstName: "John",
								lastName: "Doe",
								deskId: 4,
							},
							{
								id: 5,
								firstName: "John",
								lastName: "Doe",
								deskId: 5,
							},
							{
								id: 6,
								firstName: "John",
								lastName: "Doe",
								deskId: 6,
							},
							{
								id: 7,
								firstName: "John",
								lastName: "Doe",
								deskId: 7,
							},
							{
								id: 8,
								firstName: "John",
								lastName: "Doe",
								deskId: 8,
							},
							{
								id: 9,
								firstName: "John",
								lastName: "Doe",
								deskId: 9,
							},
							{
								id: 10,
								firstName: "John",
								lastName: "Doe",
								deskId: 10,
							},
							{
								id: 11,
								firstName: "John",
								lastName: "Doe",
								deskId: 11,
							},
							{
								id: 12,
								firstName: "John",
								lastName: "Doe",
								deskId: 12,
							},
							{
								id: 13,
								firstName: "John",
								lastName: "Doe",
								deskId: 13,
							},
							{
								id: 14,
								firstName: "John",
								lastName: "Doe",
								deskId: 14,
							},
							{
								id: 15,
								firstName: "John",
								lastName: "Doe",
								deskId: 15,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 0,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [0],
							},
							{
								id: 1,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [1],
							},
							{
								id: 2,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [2],
							},
							{
								id: 3,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [3],
							},
							{
								id: 4,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [4],
							},
							{
								id: 5,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [5],
							},
							{
								id: 6,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [6],
							},
							{
								id: 7,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [7],
							},
							{
								id: 8,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [8],
							},
							{
								id: 9,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [9],
							},
							{
								id: 10,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [10],
							},
							{
								id: 11,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [11],
							},
							{
								id: 12,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [12],
							},
							{
								id: 13,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [13],
							},
							{
								id: 14,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [14],
							},
							{
								id: 15,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [15],
							},
						],
					},
				],
			},
			{
				id: 1,
				plans: [
					{
						id: 0,
						nom: "1er Etage",
						picture: {
							src: "",
							alt: "Plan du 1er Etage",
						},
						collaborators: [
							{
								id: 16,
								firstName: "John",
								lastName: "Doe",
								deskId: 16,
							},
							{
								id: 17,
								firstName: "John",
								lastName: "Doe",
								deskId: 17,
							},
							{
								id: 18,
								firstName: "John",
								lastName: "Doe",
								deskId: 18,
							},
							{
								id: 19,
								firstName: "John",
								lastName: "Doe",
								deskId: 19,
							},
							{
								id: 20,
								firstName: "John",
								lastName: "Doe",
								deskId: 20,
							},
							{
								id: 21,
								firstName: "John",
								lastName: "Doe",
								deskId: 21,
							},
							{
								id: 22,
								firstName: "John",
								lastName: "Doe",
								deskId: 22,
							},
							{
								id: 23,
								firstName: "John",
								lastName: "Doe",
								deskId: 23,
							},
							{
								id: 24,
								firstName: "John",
								lastName: "Doe",
								deskId: 24,
							},
							{
								id: 25,
								firstName: "John",
								lastName: "Doe",
								deskId: 25,
							},
							{
								id: 26,
								firstName: "John",
								lastName: "Doe",
								deskId: 26,
							},
							{
								id: 27,
								firstName: "John",
								lastName: "Doe",
								deskId: 27,
							},
							{
								id: 28,
								firstName: "John",
								lastName: "Doe",
								deskId: 28,
							},
							{
								id: 29,
								firstName: "John",
								lastName: "Doe",
								deskId: 29,
							},
							{
								id: 30,
								firstName: "John",
								lastName: "Doe",
								deskId: 30,
							},
							{
								id: 31,
								firstName: "John",
								lastName: "Doe",
								deskId: 31,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 16,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [16],
							},
							{
								id: 17,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [17],
							},
							{
								id: 18,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [18],
							},
							{
								id: 19,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [19],
							},
							{
								id: 20,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [20],
							},
							{
								id: 21,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [21],
							},
							{
								id: 22,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [22],
							},
							{
								id: 23,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [23],
							},
							{
								id: 24,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [24],
							},
							{
								id: 25,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [25],
							},
							{
								id: 27,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [27],
							},
							{
								id: 28,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [28],
							},
							{
								id: 29,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [29],
							},
							{
								id: 30,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [30],
							},
							{
								id: 31,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [31],
							},
							{
								id: 32,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [32],
							},
						],
					},
				],
			},
			{
				id: 2,
				plans: [
					{
						id: 0,
						nom: "2nd Etage",
						picture: {
							src: "",
							alt: "Plan du 2nd Etage",
						},
						collaborators: [
							{
								id: 32,
								firstName: "John",
								lastName: "Doe",
								deskId: 32,
							},
							{
								id: 33,
								firstName: "John",
								lastName: "Doe",
								deskId: 33,
							},
							{
								id: 34,
								firstName: "John",
								lastName: "Doe",
								deskId: 34,
							},
							{
								id: 35,
								firstName: "John",
								lastName: "Doe",
								deskId: 35,
							},
							{
								id: 36,
								firstName: "John",
								lastName: "Doe",
								deskId: 36,
							},
							{
								id: 37,
								firstName: "John",
								lastName: "Doe",
								deskId: 37,
							},
							{
								id: 38,
								firstName: "John",
								lastName: "Doe",
								deskId: 38,
							},
							{
								id: 39,
								firstName: "John",
								lastName: "Doe",
								deskId: 39,
							},
							{
								id: 40,
								firstName: "John",
								lastName: "Doe",
								deskId: 40,
							},
							{
								id: 41,
								firstName: "John",
								lastName: "Doe",
								deskId: 41,
							},
							{
								id: 42,
								firstName: "John",
								lastName: "Doe",
								deskId: 42,
							},
							{
								id: 43,
								firstName: "John",
								lastName: "Doe",
								deskId: 43,
							},
							{
								id: 44,
								firstName: "John",
								lastName: "Doe",
								deskId: 44,
							},
							{
								id: 45,
								firstName: "John",
								lastName: "Doe",
								deskId: 45,
							},
							{
								id: 46,
								firstName: "John",
								lastName: "Doe",
								deskId: 46,
							},
							{
								id: 47,
								firstName: "John",
								lastName: "Doe",
								deskId: 47,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 33,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [33],
							},
							{
								id: 34,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [34],
							},
							{
								id: 35,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [35],
							},
							{
								id: 36,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [36],
							},
							{
								id: 37,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [37],
							},
							{
								id: 38,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [38],
							},
							{
								id: 39,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [39],
							},
							{
								id: 40,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [40],
							},
							{
								id: 41,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [41],
							},
							{
								id: 42,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [42],
							},
							{
								id: 43,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [43],
							},
							{
								id: 44,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [44],
							},
							{
								id: 45,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [45],
							},
							{
								id: 46,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [46],
							},
							{
								id: 47,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [47],
							},
							{
								id: 48,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [48],
							},
						],
					},
				],
			},
			{
				id: 3,
				plans: [
					{
						id: 0,
						nom: "3ème Etage",
						picture: {
							src: "",
							alt: "Plan du 3ème Etage",
						},
						collaborators: [
							{
								id: 48,
								firstName: "John",
								lastName: "Doe",
								deskId: 48,
							},
							{
								id: 49,
								firstName: "John",
								lastName: "Doe",
								deskId: 49,
							},
							{
								id: 50,
								firstName: "John",
								lastName: "Doe",
								deskId: 50,
							},
							{
								id: 51,
								firstName: "John",
								lastName: "Doe",
								deskId: 51,
							},
							{
								id: 52,
								firstName: "John",
								lastName: "Doe",
								deskId: 52,
							},
							{
								id: 53,
								firstName: "John",
								lastName: "Doe",
								deskId: 53,
							},
							{
								id: 54,
								firstName: "John",
								lastName: "Doe",
								deskId: 54,
							},
							{
								id: 55,
								firstName: "John",
								lastName: "Doe",
								deskId: 55,
							},
							{
								id: 56,
								firstName: "John",
								lastName: "Doe",
								deskId: 56,
							},
							{
								id: 57,
								firstName: "John",
								lastName: "Doe",
								deskId: 57,
							},
							{
								id: 58,
								firstName: "John",
								lastName: "Doe",
								deskId: 58,
							},
							{
								id: 59,
								firstName: "John",
								lastName: "Doe",
								deskId: 59,
							},
							{
								id: 60,
								firstName: "John",
								lastName: "Doe",
								deskId: 60,
							},
							{
								id: 61,
								firstName: "John",
								lastName: "Doe",
								deskId: 61,
							},
							{
								id: 62,
								firstName: "John",
								lastName: "Doe",
								deskId: 62,
							},
							{
								id: 63,
								firstName: "John",
								lastName: "Doe",
								deskId: 63,
							},
						],
						receptionMaxcapacity: 16,
						currentReceptionCapacity: 16,
						bureaux: [
							{
								id: 49,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [49],
							},
							{
								id: 50,
								name: "Bureau A002",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [50],
							},
							{
								id: 51,
								name: "Bureau A003",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [51],
							},
							{
								id: 52,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [52],
							},
							{
								id: 53,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [53],
							},
							{
								id: 54,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [54],
							},
							{
								id: 55,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [55],
							},
							{
								id: 56,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [56],
							},
							{
								id: 57,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [57],
							},
							{
								id: 58,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [58],
							},
							{
								id: 59,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [59],
							},
							{
								id: 60,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [60],
							},
							{
								id: 61,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [61],
							},
							{
								id: 62,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [62],
							},
							{
								id: 63,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [63],
							},
							{
								id: 64,
								name: "Bureau A001",
								floorsNumber: 1,
								quantitePlaces: 1,
								customers: [
									{
										id: 0,
										firstName: "John",
										lastName: "Doe",
										password: "myawesomepasswordhashed",
									},
								],
								collaboratorsIds: [64],
							},
						],
					},
				],
			},
		],
		receptionMaxcapacity: 64,
		currentReceptionCapacity: 64,
		officesNumber: 64,
		occupancyStatistics: 100,
		picture: {
			src: "/images/buildings/batiment-2.png",
			alt: "Image du Bâtiment B",
		},
	},
]
